version: '2.4'
services:

  web:
    image: rails-tanzfabrik
    build:
      context: .
    restart: always
#    command: /bin/bash
    command: bash -c "bundle check && rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    env_file:
      - ./.env
    volumes:
      - .:/app:cached
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
    # volumes_from: 
    #   - gemcache
    depends_on:
      # gemcache:
      #   condition: service_started
      db:
        condition: service_healthy

  webpacker:
    image: rails-tanzfabrik
    command: ["./scripts/start_webpack_dev.sh"]
    volumes:
      - .:/app:cached
    ports:
      - "3035:3035"
    environment:
      - RAILS_ENV=development      

  db:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.data/db:/var/lib/postgresql/data:cached
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s      

  # gemcache:
  #   image: busybox
  #   volumes:
  #     - /gemcache

  adminer:
    image: adminer
    ports:
      - 3001:8080
    depends_on:
      - db     