version: '2.4'
services:

  web:
    build: .
    restart: always
#    command: /bin/bash
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    env_file:
      - ./.env
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.data/db:/var/lib/postgresql/data
      - ./.data:/data
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s      

  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - db     