# when adding a new form-field to the content_module model, you need to also update the list of form-fields in active_admin.js (module_types you define here are picked up automatically)

# note: rails app needs to restart for changes in this config to take effect
# translations are in config/locales under content_modules key

feature:
  style-options:
    - default
    - left
  sections:
    - buehne
    - schule
    - fabrik
  form-fields:
    - headline
    - special_text
    - rich_content_1
  downloads: false
page_intro:
  style-options:
    - default
  sections:
    - buehne
    - schule
    - fabrik    
  form-fields:
    - headline
    - special_text
    - sub
    - rich_content_1
    - link_title
    - link_href
    - parameter
page_intro_magazine:
  style-options:
    - default
  sections:
    - buehne
    - schule
    - fabrik    
  form-fields:
    - headline
    - sub
  downloads: false
content_element:
  style-options:
    - default
  sections:
    - buehne
    - schule
    - fabrik
  form-fields:
    - headline
    - special_text
    - rich_content_1
    - link_title
    - link_href
content_2_columns:
  style-options:
    - default
  sections:
    - buehne
    - schule
    - fabrik
  form-fields:
    - headline
    - rich_content_1
    - rich_content_2
  images: false    
content_element_magazine:
  style-options:
    - default
    - centered
    - large_left
    - large_right
  sections:
    - buehne
    - schule
    - fabrik
  form-fields:
    - rich_content_1
reference:
  style-options:
    - default
  sections:
    - buehne
    - schule
    - fabrik
    - festival
  form-fields:
    - headline
    - sub
    - rich_content_1    
    - link_title
    - link_href
slideshow:
  style-options:
    - default
    - fixed_height
  sections:
    - buehne
    - schule
    - fabrik
  form-fields:
    - headline
    - link_title
    - link_href    
  downloads: false
submenu_divider:
  style-options:
    - default
  form-fields:
    - headline
    - parameter
  images: false
  downloads: false
people_gallery:
  style-options:
    - default
    - large
  form-fields:
    - headline
    - parameter
  sections:
    - buehne
    - schule
    - fabrik     
  images: false
  downloads: false
kursplan:
  style-options:
    - default
  form-fields:
    - parameter
  images: false
  downloads: false
studio:
  form-fields:
    - parameter
  images: false
  downloads: false
festival_vorschau:
  style-options:
    - default
  form-fields:
    - parameter
  images: false
  downloads: true
festival_programm:
  style-options:
    - default
  form-fields:
    - parameter
  images: false
  downloads: false
festival_archiv:
  style-options:
  form-fields:
    - parameter
  images: false
  downloads: false
custom_html:
  form-fields: 
    - custom_html
  images: false
  downloads: false
video:
  form-fields:
    - headline
    - parameter
    - link_href
    - link_title
  images: false
  downloads: false
newsletter:
  form-fields:
    - headline
    - rich_content_1
  images: false
  downloads: false
accordeon_element:
  form-fields:
    - headline
    - rich_content_1
  images: false
  downloads: false
today: 
  form-fields:
    - headline
  images: false
  downloads: false
default:
  style-options: 
    - default
  form-fields:
    - super
    - headline
    - sub
    - special_text
    - rich_content_1
    - rich_content_2
    - custom_html
    - parameter
    - link_title
    - link_href








