# content_module model reference for form fields
#t.string "super"
#t.string "headline"
#t.string "sub"
#t.text "special_text"
# rich_content_1
# rich_content_2

# a list of all existing form-fields must be manually updates in active_admin.js


page-intro:
  style-options:
    - default
    - magazine
  form-fields:
    - super 
    - headline
    - sub
    - rich_content_1
content-element:
  style-options:
    - default
    - centered
    - 2-column
  form-fields:
    - super 
    - headline
    - sub



