# when adding a new form-field to the content_module model, you need to also update the list of form-fields in active_admin.js (module_types you define here are picked up automatically)

# note: rails app needs to restart for changes in this config to take effect
# translations are in config/locales under content_modules key

page_intro:
  style-options:
    - default
    - magazine
  form-fields:
    - headline
    - special_text
    - rich_content_1
content_2_columns:
  style-options:
    - default
  form-fields:
    - headline
    - rich_content_1
    - rich_content_2
  images: false
content_element:
  style-options:
    - default
    - centered
  form-fields:
    - headline
    - special_text
    - rich_content_1
submenu_divider:
  style-options:
    - default
  form-fields:
    - headline
    - parameter
  images: false
  downloads: false
people_gallery:
  style-options:
    - default
  form-fields:
    - parameter
  images: false
  downloads: false
kursplan:
  style-options:
    - default
  form-fields:
    - parameter
  images: false
  downloads: false
festival_vorschau:
  style-options:
    - default
  form-fields:
    - parameter
festival_programm:
  style-options:
    - default
  form-fields:
    - parameter
  images: false
  downloads: false
festival_archiv:
  style-options:
  form-fields:
  images: false
  downloads: false
default:
  style-options: 
    - default
  form-fields:
    - super
    - headline
    - sub
    - special_text
    - rich_content_1
    - rich_content_2
    - custom_html
    - parameter








