# note: rails app needs to restart for changes in this config to take effect
# translations are in config/locales under content_modules key

feature:
  style-options:
    - default
    - left
  sections:
    - buehne
    - schule
    - fabrik
    - festival
  form-fields:
    - headline
    - special_text
    - rich_content_1
    - link_href
  downloads: false
  border-bottom-options: true
page_intro:
  style-options:
    - default
    - small_headline_font
  sections:
    - buehne
    - schule
    - fabrik    
  form-fields:
    - headline
    - special_text
    - rich_content_1
    - rich_content_2
    - link_title
    - link_href
    - parameter
  border-bottom-options: true
page_intro_magazine:
  style-options:
    - default
    - small_headline_font
  sections:
    - buehne
    - schule
    - fabrik    
  form-fields:
    - headline
    - sub
  downloads: false
  border-bottom-options: true
content_element:
  style-options:
    - default
  sections:
    - buehne
    - schule
    - fabrik
  form-fields:
    - headline
    - special_text
    - rich_content_1
    - link_title
    - link_href
    - parameter
  border-bottom-options: true
content_2_columns:
  style-options:
    - default
    - indent_more
  sections:
    - buehne
    - schule
    - fabrik
  form-fields:
    - headline
    - rich_content_1
    - rich_content_2
  images: false    
  border-bottom-options: true
content_element_magazine:
  style-options:
    - default
    - centered
    - large_left
    - large_right
  sections:
    - buehne
    - schule
    - fabrik
  form-fields:
    - rich_content_1
  border-bottom-options: true
image_element_magazine:
  style-options:
    - default
  sections:
    - buehne
    - schule
    - fabrik
  form-fields:
    - headline
    - rich_content_1
  downloads: false
  border-bottom-options: true
reference:
  style-options:
    - default
  sections:
    - buehne
    - schule
    - fabrik
    - festival
  form-fields:
    - headline
    - sub
    - special_text
    - rich_content_1    
    - link_title
    - link_href
  border-bottom-options: true
slideshow:
  style-options:
    - default
    - fixed_height
  sections:
    - buehne
    - schule
    - fabrik
  form-fields:
    - headline
    - link_title
    - link_href    
  downloads: false
  border-bottom-options: true
submenu_divider:
  style-options:
    - default
  form-fields:
    - headline
    - parameter
  images: false
  downloads: false
  border-bottom-options: false
people_gallery:
  style-options:
    - default
    - large
  form-fields:
    - headline
    - parameter
  sections:
    - buehne
    - schule
    - fabrik     
  images: false
  downloads: false
  border-bottom-options: true
kursplan:
  style-options:
    - default
  form-fields:
    - parameter
  images: false
  downloads: false
studio:
  form-fields:
    - parameter
  images: false
  downloads: false
  border-bottom-options: false
festival_vorschau:
  style-options:
    - default
  form-fields:
    - parameter
  images: false
  downloads: true
  border-bottom-options: false
festival_programm:
  style-options:
    - default
  form-fields:
    - parameter
  images: false
  downloads: false
  border-bottom-options: false
festival_logos:
  style-options:
    - default
  form-fields:
  downloads: false
  border-bottom-options: false
festival_archiv:
  style-options:
  form-fields:
    - parameter
  images: false
  downloads: false
  border-bottom-options: false
custom_html:
  form-fields: 
    - custom_html
  images: false
  downloads: false
  border-bottom-options: false
video:
  form-fields:
    - headline
    - parameter
    - link_href
    - link_title
  images: false
  downloads: false
  border-bottom-options: true
newsletter:
  form-fields:
    - headline
    - rich_content_1
  images: false
  downloads: false
  border-bottom-options: true
accordeon_headline:
  form-fields:
    - headline
  images: false
  downloads: false
  border-bottom-options: true
accordeon_element:
  form-fields:
    - headline
    - rich_content_1
  images: false
  downloads: false
  border-bottom-options: true
today: 
  form-fields:
    - headline
  images: false
  downloads: false
  border-bottom-options: true
profitraining:
  form-fields: []
  images: false
  downloads: false
  border-bottom-options: true 
programm:
  form-fields:
    - parameter
  images: false
  downloads: false
  border-bottom-options: false
default:
  style-options: 
    - default
  form-fields:
    - super
    - headline
    - sub
    - special_text
    - rich_content_1
    - rich_content_2
    - custom_html
    - parameter
    - link_title
    - link_href
  border-bottom-options: false








