name: Deploy dokku

on:
  push:
    branches:
      - relaunch2020

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: relaunch2020
      - id: deploy
        name: Deploy to dokku
        uses: idoberko2/dokku-deploy-github-action@v1
        with:
            ssh-private-key: ${{ secrets.DOKKU_SSH_PRIVATE_KEY }}
            dokku-host: 'tanzfabrik.intergestalt.cloud'
            app-name: 'relaunch2020'
            git-push-flags: '--force'
